// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserServer service

func NewUserServerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserServer service

type UserServerService interface {
	UserInfo(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*PutResponse, error)
}

type userServerService struct {
	c    client.Client
	name string
}

func NewUserServerService(name string, c client.Client) UserServerService {
	return &userServerService{
		c:    c,
		name: name,
	}
}

func (c *userServerService) UserInfo(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*PutResponse, error) {
	req := c.c.NewRequest(c.name, "UserServer.UserInfo", in)
	out := new(PutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserServer service

type UserServerHandler interface {
	UserInfo(context.Context, *GetRequest, *PutResponse) error
}

func RegisterUserServerHandler(s server.Server, hdlr UserServerHandler, opts ...server.HandlerOption) error {
	type userServer interface {
		UserInfo(ctx context.Context, in *GetRequest, out *PutResponse) error
	}
	type UserServer struct {
		userServer
	}
	h := &userServerHandler{hdlr}
	return s.Handle(s.NewHandler(&UserServer{h}, opts...))
}

type userServerHandler struct {
	UserServerHandler
}

func (h *userServerHandler) UserInfo(ctx context.Context, in *GetRequest, out *PutResponse) error {
	return h.UserServerHandler.UserInfo(ctx, in, out)
}
