// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeCheeseCat(msg string) *cheeseCat {
	mainAnimal := newAnimal(msg)
	mainCatOne := newCatOne(mainAnimal)
	mainCheeseCat := newCheeseCat(mainCatOne)
	return mainCheeseCat
}
